# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y




# ====================== ИМЯ КЛАВИАТУРЫ ======================
CONFIG_ZMK_KEYBOARD_NAME="DEX Corne"

# Можно сделать разные имена для левой и правой половин:
# CONFIG_ZMK_KEYBOARD_NAME="Evgeniy Corne Left"   # для левой
# CONFIG_ZMK_KEYBOARD_NAME="Evgeniy Corne Right"  # для правой

# BLE настройки
#CONFIG_ZMK_BLE=y
#CONFIG_ZMK_BLE_CLEAR_BONDS_ON_RESET=y

# OLED (nice!view)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# RGB (если есть подсветка)
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# Автоспящий режим (30 секунд)
#CONFIG_ZMK_IDLE_TIMEOUT=30000